{
 "title": "NVIDIA GPU & vGPU Monitoring",
 "tags": [
  "prometheus",
  "gpu",
  "vgpu"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nvidia_smi_gpu_info, host)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvidia_smi_gpu_info{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "VM Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "nvidia_vgpu_info{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Active vGPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvidia_vgpu_info{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GPU Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "nvidia_smi_gpu_info{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "GPU Memory (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_total_bytes{host=~\"$host\"}",
     "legendFormat": "GPU Total: {{gpu_name}}"
    },
    {
     "expr": "nvidia_smi_memory_used_bytes{host=~\"$host\"}",
     "legendFormat": "GPU Used: {{gpu_name}}"
    }
   ]
  },
  {
   "title": "vGPU Memory (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_vgpu_memory_bytes{type=\"Total\",host=~\"$host\"}",
     "legendFormat": "vGPU Total: {{vm_name}}"
    },
    {
     "expr": "nvidia_vgpu_memory_bytes{type=\"Used\",host=~\"$host\"}",
     "legendFormat": "vGPU Used: {{vm_name}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{host=~\"$host\"}",
     "legendFormat": "GPU: {{gpu_name}}"
    }
   ]
  },
  {
   "title": "vGPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_vgpu_utilization_percent{type=\"Gpu\",host=~\"$host\"}",
     "legendFormat": "vGPU: {{vm_name}}"
    },
    {
     "expr": "nvidia_vgpu_utilization_percent{type=\"Memory\",host=~\"$host\"}",
     "legendFormat": "vGPU Mem: {{vm_name}}"
    }
   ]
  }
 ]
}